### ISSUE TITLE
Would you rather...

### ISSUE THREAD

**Issue by assertchris** [greydnls/ama#10]
1. B-list horror movie and a huge bowl of double-toffee ice-cream 
2. ok-cup-of-starbucks and a couple of friends at 3am

and why?

**Comment by greydnls** [comment]
Can I watch the movie with some ice cream and coffee and friends at three in the morning? Cause I'm greedy like that. 

Honestly though, the last one. There's plenty of time in the world to watch B-list horror movies (and I do that as much as I can manage). But being with friends at 3am, whether that's the end of your night or the start of your day... those kinds of things are rare, and when they happen, they're beautiful. 

When I'm old and lying about thinking about my life, I'd rather have more of the latter memories to look back on than the former.

**Comment by assertchris** [comment]
Correct.
