### ISSUE TITLE
What books are balancing your furniture? 

### ISSUE THREAD

**Issue by assertchris** [greydnls/ama#11]

**Comment by greydnls** [comment]
-_-

Vintage Math books, mostly. They're old, but very sturdy and they hold up the couch well while I wait for ikea to send me replacement legs.

**Comment by greydnls** [comment]
![image](https://cloud.githubusercontent.com/assets/1276798/9725646/8343a9ca-55b5-11e5-9845-931ee6603574.png)

**Comment by greydnls** [comment]
I'd have to move the couch for the other side and I'm lazy.
