### ISSUE TITLE
How long have you been crafting code? How often do you get in flow-state/in-the-zone?

### ISSUE THREAD

**Issue by aretecode** [greydnls/ama#17]

**Comment by greydnls** [comment]
I don't even know if I can say I'm "crafting code" now. I've been writing code professionally for about 4 years, though I started tinkering with stuff when I was about 13. 

How often do I get in the zone? Hmm, that's a hard question to answer. I would say getting truly immersed in something isn't so much a matter of frequency, so much as what I'm working on. If I'm working on something awesome I can get in the zone daily, or several times a day. 

If I'm working on something less enticing, getting in the zone will be rare and it's more a case of trudging along.
