### ISSUE TITLE
What does your diet usually comprise? 

### ISSUE THREAD

**Issue by aretecode** [greydnls/ama#18]

**Comment by greydnls** [comment]
This is a tricky question. My current diet sucks. I'm trying to fix it, but it's a work in progress. 

Breakfast: Coffee. I realize that's terrible, so I'm trying to make myself eat a bowl of granola and some fruit. 

Lunch: Normally skip it, sometimes have hummus & pretzels.  (Again, I realize this is terrible practice). 

Dinner: I LOVE to cook, and I like to keep my menu prettied varied day to day and week to week. Things I eat often: Chicken, steak, seafood. Try to keep a lot of veggies on the plate. I like asparagus, salads, green beans, kale, brussel sprouts. Generally, if it's leafy and green, I'll eat it.  Try to keep starches minimal, but I do like quinoa, rice and occasionally pasta. Oh, and potatoes, but not often. 

A lot of my diet revolves around my kids. I try to strike a nice balance between cooking things I know they'll eat and new things I want them to try. If there's something that they say they don't like, I usually keep trying to get them to eat it by cooking it differently. It's a mix of a) keeping them healthy and b) teaching them to be adventurous with their pallets.
