### ISSUE TITLE
Have you ever tried Polymer?

### ISSUE THREAD

**Issue by tenhobi** [greydnls/ama#27]

**Comment by greydnls** [comment]
No I haven't. Glancing over the docs it looks pretty interesting. have you used it? Do you like it?

**Comment by tenhobi** [comment]
First time I have met Polymer on Hackathon in Prague (where we also tried and used Dart). We have tried their material design elements and we really didn't like the way of doing it. 

Time passed and I have started using Polymer (**v1.0**) on our desktop in-browser manager app http://nottelo.com. And I love it even thought it is not super amazing yet and it still have some things to improve. 

With Polymer we brutally reduced our HTML structure from redundant code (in "index.html") to only few arranged custom elements. We do ourselves custom-elements and now we have around 35.

It is more better write bellow, which renders for example some nav logo, social icons (from nav-bar) + items. Tottaly semantic and tottaly awesome. Better than a milion of divs, spans, imgs...  

``` html
<nav-bar>
  <nav-item>Autíčko</nav-item>
  <nav-item>Kočička</nav-item>
  <nav-item>Twilight Sparkle</nav-item>
</nav-bar>
```

Polymer also polyfills custom properties and you can use them in CSS (connected from attribute). You just call observe (on attribute change value) event, where you save the value of element attribute into the custom property. Polymer create `<style>` for each value and connect it with the element. So something like bellow is not a reall problem. :smirk_cat: 

``` html
<my-tag color="#abcabc">School</my-tag>
<my-tag color="rgb(125, 200, 13)">WORK</my-tag>
<my-tag color="red">ASAP</my-tag>
```

That is what I like on Polymer. It makes reall web modules. Also each Polymer element has own modular styles. :+1:
