### ISSUE TITLE
What was the first personal PHP project you released to the public that you're very proud of?

### ISSUE THREAD

**Issue by jcomack** [greydnls/ama#3]

**Comment by greydnls** [comment]
Probably my most favorite is (Gitodo)[http://github.com/kayladnls/gitodo). 

It was a random idea I had one night and I went from 0 to a working thing in a weekend. I'd never used bash before, so it was a learning experience and it was pretty difficult, but in the end it works pretty nicely.

**Comment by vivekfyi** [comment]
@greydnls  but its not PHP Project.
