### ISSUE TITLE
Remote parenting

### ISSUE THREAD

**Issue by nlipke** [greydnls/ama#5]
What tips do you have for parents who are away from their kids. Do the younger ones deal well with FaceTime/Hangouts?

**Comment by greydnls** [comment]
My sons are 3 (almost 4) and 5 (almost  6). When I moved to NYC they stayed with their dad for the summer. I would skype them every night. He'd have me call right in the middle of dinner and he'd leave the TV on (This bugged the b'jesus out of me). The boys didn't want to talk to me much, and that hurt a lot, but I kept trying. They can be pretty into skype when they want to, but often loose interest pretty quickly, especially if there are other things going on in the room. 

They're with me now, and we call their dad every night before bed. I make sure that there's no tv/video games on, and they stay pretty focused and talk to him for 10-15 minutes most nights. 

My oldest boy is having a really hard time adjusting to the divorce, so I promised him that he can call his dad anytime, no matter what. Sometimes that means that he wakes up in the middle of the night with a nightmare and wants to call. Sometimes it means first thing in the morning he's sitting on my chest asking to call. Whatever it takes. 

As with any parenting, the focus for me is to make it as healthy and easy for them as possible. If you love your kids (i'm sure you do), you just have to make sure they know that. The rest will fall into place.
