### ISSUE TITLE
What inspired you to get into software development?

### ISSUE THREAD

**Issue by jcarouth** [greydnls/ama#7]

**Comment by greydnls** [comment]
I used to hack on websites when I was a kid, just html and css. I remember how mind blowing it was when they came out with iframes. YOU CAN THEM AAAAAANYWHERE! 

Then i went to college, studied a bunch of different things. For a while I wanted to be a cop and studied criminal justice. Eventually I sat with an advisor and we discussed computer science. I saw how much math was involved and thought "hey, I'm good at math. I love computers. Let's do that" 

The first class I took was c++. I spent hours trying to make my first assignment work. I  was beyond frustrated. Then it compiled for the first time, and it was beyond magic. I was hooked and knew I could never do anything else.
