### ISSUE TITLE
What profession, non-tech and non-criminal-justice related, could you see yourself having done?

### ISSUE THREAD

**Issue by rcatlin** [greydnls/ama#8]
Had to add "non-criminal-justice" as you mentioned that was your major in college ;)

**Comment by greydnls** [comment]
Linguistics. I'm completely fascinated about the evolution of languages over time. Constantly looking up where words came from, what other words they're related to, word parts, etc. It's absolutely amazing.

Though, I don't know how marketable that is, or what kind of career outlook it has. Maybe after I make my millions I'll switch to that. 

Even better! I could mix the two. Linguistics software ftw.
