### ISSUE TITLE
Have you seen my chickens?

### ISSUE THREAD

**Issue by bencorlett** [greydnls/ama#9]
I left the side gate open, and they've disappeared when I took the dog for a run.

**Comment by bencorlett** [comment]
![img_9770](https://cloud.githubusercontent.com/assets/181919/9724215/f2a2ee78-5616-11e5-846c-c8bf14aef597.jpg)

Found them! They're in next door's front garden. #mollyandpolly

**Comment by greydnls** [comment]
Don't you have a third one?

**Comment by bencorlett** [comment]
You remember! I had 4, Henny, Penny, Molly and Polly.

![img_5374](https://cloud.githubusercontent.com/assets/181919/9725421/809b67d0-5628-11e5-88d9-baf2c6b77a04.jpg)

Henny is in the far background in this photo and looks just like Penny (who my mate Andrew is holding here).

**Comment by bencorlett** [comment]
Penny turned out to be a rooster, so she became Kenny.

Kenny died :(
